### ISSUE TITLE
Issue: flag redefined: graceful

### ISSUE THREAD

**Issue by sathishkumar-kb** [sergeylanzman/newrelic_beego#7]
./<folder_name> flag redefined: graceful
panic: ./<folder_name> flag redefined: graceful

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc4200c6000, 0xd64c80, 0x1149923, 0xc88e9a, 0x8, 0xc9fbff, 0x21)
	/usr/local/go/src/flag/flag.go:810 +0x540
flag.BoolVar(0x1149923, 0xc88e9a, 0x8, 0xc420179a00, 0xc9fbff, 0x21)
	/usr/local/go/src/flag/flag.go:589 +0x72
github.com/sergeylanzman/newrelic_beego/vendor/github.com/astaxie/beego/grace.init.0()
	/<project_path>/go/src/github.com/sergeylanzman/newrelic_beego/vendor/github.com/astaxie/beego/grace/grace.go:93 +0x60

I am getting above error when I execute **bee run**. 

Configurations:

├── Beego     : 1.9.2
├── GoVersion : go1.10
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /home/-username-/projects/go
├── GOROOT    : /usr/local/go

**Comment by sathishkumar-kb** [comment]
@sergeylanzman Any idea why I am getting this error?

**Comment by sergeylanzman** [comment]
@sathishkumar-kb You use dep? I see it's because vendor folder in newrelic_beego has beego. If you use newrelic_beego in your project with dep. dep resolve this.

**Comment by sathishkumar-kb** [comment]
@sergeylanzman I am not using dep. I have issued **go get ./...** to install the dependencies. What I understand is when I use **dep**, will solve this issue for me. Am I right? Please suggest me.

**Comment by gnanakeethan** [comment]
@sathishkumar-kb  Do this. 

Just browse into this new_relic directory, delete the vendor folder. This repository should not have a vendor folder by itself.

**Comment by vennapusachenna** [comment]
May i know dep ??
